spring:
  freemarker:
    cache: true
  jackson:
    serialization:
      indent-output: false

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    com.whitestork: WARN
    org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter: OFF

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

management:
  endpoint:
    health:
      show-details: when_authorized

resend:
  sender-email: Биометрик <noreply@biometric.com>